# -*- coding: utf-8 -*-
"""cactpot_total_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tWR8_csCi4TOWtcf2VYW54tMcUQzDiQN
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import math as ma
import seaborn as sns
import scipy.stats as st

rfile1 = open("rewards_output.txt","r")
rdata1 = rfile1.readlines()
rlist1 = rdata1[0].split(" ")

rlist1 = rlist1[:3000]
rintlist1 = [int(i) for i in rlist1]

rfile2 = open("rewards_output_2.txt","r")
rdata2 = rfile2.readlines()
rlist2 = rdata2[0].split(" ")

rlist2 = rlist2[:3000]
rintlist2 = [int(i) for i in rlist2]

rfile3 = open("rewards_output_3.txt","r")
rdata3 = rfile3.readlines()
rlist3 = rdata3[0].split(" ")

rlist3 = rlist3[:3000]
rintlist3 = [int(i) for i in rlist3]

rfile4 = open("rewards_output_4.txt","r")
rdata4 = rfile4.readlines()
rlist4 = rdata4[0].split(" ")

rlist4 = rlist4[:3000]
rintlist4 = [int(i) for i in rlist4]

rfile5 = open("rewards_output_5.txt","r")
rdata5 = rfile5.readlines()
rlist5 = rdata5[0].split(" ")

rlist5 = rlist5[:3000]
rintlist5 = [int(i) for i in rlist5]

sfile1 = open("sums_output.txt","r")
sdata1 = sfile1.readlines()
slist1 = sdata1[0].split(" ")

slist1 = slist1[:3000]
sintlist1 = [int(i) for i in slist1]

sfile2 = open("sums_output_2.txt","r")
sdata2 = sfile2.readlines()
slist2 = sdata2[0].split(" ")

slist2 = slist2[:3000]
sintlist2 = [int(i) for i in slist2]

sfile3 = open("sums_output_3.txt","r")
sdata3 = sfile3.readlines()
slist3 = sdata3[0].split(" ")

slist3 = slist3[:3000]
sintlist3 = [int(i) for i in slist3]

sfile4 = open("sums_output_4.txt","r")
sdata4 = sfile4.readlines()
slist4 = sdata4[0].split(" ")

slist4 = slist4[:3000]
sintlist4 = [int(i) for i in slist4]

sfile5 = open("sums_output_5.txt","r")
sdata5 = sfile5.readlines()
slist5 = sdata5[0].split(" ")

slist5 = slist5[:3000]
sintlist5 = [int(i) for i in slist5]

rintlist = rintlist1 + rintlist2 + rintlist3 + rintlist4 + rintlist5
#print(len(rintlist))

sintlist = sintlist1 + sintlist2 + sintlist3 + sintlist4 + sintlist5
#print(len(sintlist))

sum = 0
index = []
average = []
for i in range(len(rintlist)):
    sum += rintlist[i]
    if (i+1) % 20 == 0:
        index.append(i+1)
        average.append(sum / (i+1))

#print(index)
#print(average)

plt.figure(figsize=(12,8))
sns.lineplot(x=index,y=average)

rcountdict = {}
for i in rintlist:
    rkeys = rcountdict.keys()
    if i in rkeys:
        rcountdict[i] += 1
    else:
        rcountdict[i] = 1

scountdict = {}
for i in sintlist:
    skeys = scountdict.keys()
    if i in skeys:
        scountdict[i] += 1
    else:
        scountdict[i] = 1

sitems = list(scountdict.items())
#print(sitems)

sitems.sort(key=lambda x:x[0])
#print(sitems)

svals = []
scts = []
for i in sitems:
    svals.append(i[0])
    scts.append(i[1])

plt.figure(figsize=(12,8))
sns.barplot(x=svals,y=scts)

rcountdict.pop(36)
rcountdict.pop(72)
rcountdict.pop(180)
rcountdict[36.07] = scountdict[7]
rcountdict[36.19] = scountdict[19]
rcountdict[72.13] = scountdict[13]
rcountdict[72.16] = scountdict[16]
rcountdict[180.15] = scountdict[15]
rcountdict[180.17] = scountdict[17]

ritems = list(rcountdict.items())
ritems.sort(key=lambda x:x[0])
#print(ritems)

rvals = []
rcts = []
for i in ritems:
    rvals.append(i[0])
    rcts.append(i[1])

plt.figure(figsize=(12,8))
sns.barplot(x=rvals,y=rcts)

sitems.sort(key=lambda x:x[1])
#print(sitems)
svals = []
scts = []
for i in sitems:
    svals.append(i[0])
    scts.append(i[1])

plt.figure(figsize=(12,8))
sns.barplot(x=svals,y=scts, order=svals)

ritems.sort(key=lambda x:x[1])
#print(ritems)
rvals = []
rcts = []
for i in ritems:
    rvals.append(i[0])
    rcts.append(i[1])
plt.figure(figsize=(12,8))
sns.barplot(x=rvals,y=rcts, order=rvals)

s10klist = []
s50klist = []
s100klist = []
s200klist = []
s500klist = []

s10k = 0
s50k = 0
s100k = 0
s200k = 0
s500k = 0

s10kc = 0
s50kc = 0
s100kc = 0
s200kc = 0
s500kc = 0

for r in rintlist:
    s10k += r
    s50k += r
    s100k += r
    s200k += r
    s500k += r

    s10kc += 1
    s50kc += 1
    s100kc += 1
    s200kc += 1
    s500kc += 1

    #print(s10kc)
    if s10k >= 10000:
        s10klist.append(s10kc)
        s10k = 0
        s10kc = 0
    if s50k >= 50000:
        s50klist.append(s50kc)
        s50k = 0
        s50kc = 0
    if s100k >= 100000:
        s100klist.append(s100kc)
        s100k = 0
        s100kc = 0
    if s200k >= 200000:
        s200klist.append(s200kc)
        s200k = 0
        s200kc = 0
    if s500k >= 500000:
        s500klist.append(s500kc)
        s500k = 0
        s500kc = 0

#print(s10klist)

#print(s50klist)

#print(s100klist)

#print(s200klist)

#print(s500klist)

#Find mean with 95% confidence interval

exprange = st.t.interval(0.95,len(rintlist)-1,loc=np.mean(rintlist),scale=st.sem(rintlist))
#print(exprange)
#print(np.mean(rintlist))
#print(st.sem(rintlist))

s10kexp = st.t.interval(0.95,len(s10klist)-1,loc=np.mean(s10klist),scale=st.sem(s10klist))
#print(s10kexp)
#print(np.mean(s10klist))
#print(st.sem(s10klist))

s50kexp = st.t.interval(0.95,len(s50klist)-1,loc=np.mean(s50klist),scale=st.sem(s50klist))
#print(s50kexp)
#print(np.mean(s50klist))
#print(st.sem(s50klist))

s100kexp = st.t.interval(0.95,len(s100klist)-1,loc=np.mean(s100klist),scale=st.sem(s100klist))
#print(s100kexp)
#print(np.mean(s100klist))
#print(st.sem(s100klist))

s200kexp = st.t.interval(0.95,len(s200klist)-1,loc=np.mean(s200klist),scale=st.sem(s200klist))
#print(s200kexp)
#print(np.mean(s200klist))
#print(st.sem(s200klist))

s500kexp = st.t.interval(0.95,len(s500klist)-1,loc=np.mean(s500klist),scale=st.sem(s500klist))
#print(s500kexp)
#print(np.mean(s500klist))
#print(st.sem(s500klist))

s7dlist = []
s14dlist = []
s30dlist = []
s90dlist = []

s7dc = 0
s14dc = 0
s30dc = 0
s90dc = 0

s7d = 0
s14d = 0
s30d = 0
s90d = 0

for r in rintlist:
    s7d += r
    s14d += r
    s30d += r
    s90d += r

    s7dc += 1
    s14dc += 1
    s30dc += 1
    s90dc += 1

    #print(s10kc)
    if s7dc == 21:
        s7dlist.append(s7d)
        s7d = 0
        s7dc = 0
    if s14dc == 42:
        s14dlist.append(s14d)
        s14d = 0
        s14dc = 0
    if s30dc == 90:
        s30dlist.append(s30d)
        s30d = 0
        s30dc = 0
    if s90dc == 270:
        s90dlist.append(s90d)
        s90d = 0
        s90dc = 0

s7dexp = st.t.interval(0.95,len(s7dlist)-1,loc=np.mean(s7dlist),scale=st.sem(s7dlist))
#print(s7dexp)
#print(np.mean(s7dlist))
#print(st.sem(s7dlist))

s14dexp = st.t.interval(0.95,len(s14dlist)-1,loc=np.mean(s14dlist),scale=st.sem(s14dlist))
#print(s14dexp)
#print(np.mean(s14dlist))
#print(st.sem(s14dlist))

s30dexp = st.t.interval(0.95,len(s30dlist)-1,loc=np.mean(s30dlist),scale=st.sem(s30dlist))
#print(s30dexp)
#print(np.mean(s30dlist))
#print(st.sem(s30dlist))

s90dexp = st.t.interval(0.95,len(s90dlist)-1,loc=np.mean(s90dlist),scale=st.sem(s90dlist))
#print(s90dexp)
#print(np.mean(s90dlist))
#print(st.sem(s90dlist))
